/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MY-PC
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        
        initComponents();
        tab();
    }
    
    /**
     *
     * @return
     */
    public ArrayList <Data>dataList() {
    ArrayList<Data> dataList= new ArrayList<>();
    try{
    String url= "jdbc:mysql://localhost:3306/business001";    
    String selectAllData= "SELECT * FROM tbl_supplier";
    Connection con;
    Statement statement;
    con=DriverManager.getConnection(url,"root","");
    statement=con.createStatement();
    ResultSet result=statement.executeQuery(selectAllData);
    Data datas;
    while(result.next()){ 
        datas= new Data(result.getInt("SupplierID"), result.getString("SupplierName"), 
            result.getString("ContactName"),result.getString("Address"),
            result.getString("City"),result.getString("PostalCode") ,result.getString("Country"));
            dataList.add(datas);
    }
        
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
    }
    
    return dataList;            
    }
    
    public void tab(){
        ArrayList<Data> list = dataList();
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        Object [] row = new Object [7];
        for (int i=0; i<list.size();i++){
                row[0]= list.get(i).getSupplierID();
                row[1]=list.get(i).getSupplierName();
                row[2]=list.get(i).getContactName();
                row[3]=list.get(i).getAddress();
                  row[4]=list.get(i).getCity();
                row[5]=list.get(i).getCountry();
                row[6]= list.get(i).getPostalCode();
                model.addRow(row);
                
        }
    }
    
    
    
//    public void show(){
//        
//            ArrayList<Data> list = dataList();
//            DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
//            Object [] row = new Object [7];
//            for (int i=0; i<list.size();i++){
//                row[0]= list.get(i).getSupplierID();
//                row[1]=list.get(i).getSupplierName();
//                row[2]=list.get(i).getContactName();
//                row[3]=list.get(i).getAddress();
//                row[4]=list.get(i).getCity();
//                row[5]=list.get(i).getCountry();
//                row[6]= list.get(i).getPostalCode();
//                
//                
//            }
//   } 
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "supply", "contact", "city", "address", "code", "country"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
